version: "3.8"

services:
  localstack:
    image: localstack/localstack:2.1.0
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/localstack:/etc/localstack/init/ready.d"
